const mongoose=require('mongoose')
const Product=new mongoose.Schema({ 
     name:{
        type:String,
        require:true
     },
     price:{    
        type:Number,
        require:true
     },
     quantity:{
        type:Number,
        require:true
     },
     image:{
        type:String,
        require:true
     },
     offer:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Offer'
     },
     shop:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Shop',
        require:true
     }
},{timestamps:true})
module.exports=mongoose.model('Product',Product)